### ISSUE TITLE
Cannot add group members

### ISSUE THREAD

**Issue by laserlab** [ubsuny/23-Homework1G4#1]
Please have a look here:

https://github.com/ubsuny/23-Homework1G1/issues/1

And do the same in this repository

**Comment by yasmensarhan27** [comment]
Hello Prof. please add those members to the team 

Usernames: sharmistharanit and poojashresthacode

Thank you in advance.

**Comment by laserlab** [comment]
Done.

Let me know if it works and then close this issue

**Comment by yasmensarhan27** [comment]
still sharmistharanit is not there

**Comment by yasmensarhan27** [comment]
Added 
Thank You @laserlab
