### ISSUE TITLE
Conflict in the chosen arithematic function

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G4#12]
G1 is doing multiplication and we are doing it too. Now what should we do?

**Comment by poojashresthacode** [comment]
G1= MULTIPLICATION
G2=HALF ADDER
G3=DIVISION
G5= DON'T KNOW
So, we G4 group can do addition as we and G1 has the same arithematic function chosen.

**Comment by yasmensarhan27** [comment]
Oooooh 
G5 is subtraction I guess

**Comment by reshnashrestha** [comment]
If we can do a similar arithmetic function or not? We(G3)  are finding division a little bit difficult.

**Comment by LinxuanHu** [comment]
yes, we G5 is doing subtraction

**Comment by sharmistharanit** [comment]
So what should we now @yasmensarhan27? We made some progress on multiplication.

**Comment by poojashresthacode** [comment]
G1 group said that as there are four arithmetic functions and 5 groups. So two groups can do multiplication. Let's ask professor.

**Comment by poojashresthacode** [comment]
@sharmistharanit

**Comment by sharmistharanit** [comment]
Okay, then it is good. @poojashresthacode
