### ISSUE TITLE
Division of Task

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G4#13]
Hy,
I am doing documentation. 
Who is doing algorithm and unit test?

**Comment by yasmensarhan27** [comment]
I'm doing the Algorithm Part

**Comment by yasmensarhan27** [comment]
I'm About to finish this part but still the result is not clear to me that it will work 
Hopefully, by tomorrow morning I'll get it done

**Comment by poojashresthacode** [comment]
GREAT!
