### ISSUE TITLE
Algorithm Part for the Multiplication Function

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G4#14]
I'm recording what I got so far:

This is for the multiplication function: 
1- we will create 3 registers q0, q1 and q2
2- assign the registers to zero state 
2- Apply Hadamard gate for the states q0 and q1 in order to have 50:50 zero and one states for each register and leave q2 in zero state
3- Add Teffoli gate to the 3 registers and the third output will return the multiplication of the 2 numbers in q0 and q1

**Comment by poojashresthacode** [comment]
why 3 registers? why not two?

**Comment by yasmensarhan27** [comment]
Teffoli gate uses 3 registers
