### ISSUE TITLE
Question about what to be include in the Algorithm, Documentation and Unit test.

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G4#16]
Do I have to include the state vector, probabilities or the Q-sphere graphs in the Algorithm or the unit test part??

What are the important things to be included??

**Comment by reshnashrestha** [comment]
In my POV, this homework project won't be this much intense. This is just about implementing basic arithmetic functions on the IBM Quantum Computer. @yasmensarhan27 
But we can have thoughts of other students as well @ubsuny/cp23-1

**Comment by yasmensarhan27** [comment]
Thank you for your response 
Really appreciated
