### ISSUE TITLE
Check the Algorithm Part

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G4#18]
Briefly,
Added 3 registers q0,q1 and q2 and adjust them at zero state 
Hadamard gate added to registers q0 and q1
Teffoli gate added to calculate the multiplication of q0 and q1 and return it to q3

**Comment by yasmensarhan27** [comment]
@poojashresthacode @sharmistharanit

**Comment by poojashresthacode** [comment]
seems right
