### ISSUE TITLE
API Key Information

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G4#19]
We can use our API key token of the IBM quantum platform to access the IBM quantum service from our local device. source: https://quantum-computing.ibm.com/account

**Comment by poojashresthacode** [comment]
can you please expain. I didn't understand what you said.

**Comment by reshnashrestha** [comment]
This is helpful for running quantum code on our local device. From the quantum computing lab website, in our profile section, there will be our user peculiar API key that can be used in our HW algorithm project.
