### ISSUE TITLE
Multiplication arithmetic function for the Homework 

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G4#2]
So, which arithmetic function are we choosing? And let's distribute the task among us. And after choosing a certain arithmetic function, let's let other groups know which function are we using.

**Comment by yasmensarhan27** [comment]
let's use Multiplication function

**Comment by poojashresthacode** [comment]
Sure! Now, how to convey to other groups that we are doing this. There is no repository in the team where we all computational physics students are member. So, we need to create repo there and add issues?

**Comment by yasmensarhan27** [comment]
First forK the project to your own branch 
after finishing the work in your branch you can merge it to the main repository 

regarding letting the other group member know, we can use issues in their repository

**Comment by sharmistharanit** [comment]
I have already forked the project and created a new branch. However, I do not understand how will we let them know that we chose multiplication for our project.

**Comment by yasmensarhan27** [comment]
I’ve made issues in their repositories to let them no
And once they replied I closed the issue

**Comment by poojashresthacode** [comment]
SOLVED
