### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework1G4#22]
I would like to run another code. Do I need to make a new branch? Or can I include the new code in the existing file?

**Comment by pratibha77118** [comment]
@sharmistharanit It would be better to make a new file in the same repository and explain what changes you have made in your new file in comparison to earlier one.  Also you can create new repository and make a new file with different code than earlier one. You can explain why this code is better than earlier one in your description section while commiting.
