### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G4#25]
Hey @ubsuny/hw1g4_cp23-1, I have done some documentation part. Can you see this in my repo?

**Comment by yasmensarhan27** [comment]
Good But I think there's still some missing parts 

the Unit test, I think

**Comment by sharmistharanit** [comment]
I can't see your repo. How do I check it? @poojashresthacode

**Comment by poojashresthacode** [comment]
you can click to my username and get into it from there.
