### ISSUE TITLE
Number of commits

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G4#29]
Hey @yasmensarhan27 , I have edited the md.file and done commit changes. But in the insights portion it shows that I have done one commit only. I don't know where I went wrong. Please help!

**Comment by yasmensarhan27** [comment]
Hi Pooja, Have you committed in your branch or where ??

**Comment by poojashresthacode** [comment]
I have committed in my branch.

**Comment by reshnashrestha** [comment]
@poojashresthacode, After committing in your branch or after making any changes you need to merge a request to you main homework branch which will be @ubsuny/hw1g4_cp23-1. Hope this helps.

**Comment by poojashresthacode** [comment]
sure
