### ISSUE TITLE
Clarification Needed

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G4#30]
The prof in the Algorithm Part mentioned that this should be included in the Algorithm part.: "generate the necessary files to run the code, not just the function" @ubsuny/cp23-1 

Can any body Clarify this to me? what are the necessary files? and BTW please check the Algorithm file on my repository and let me know if any suggestions

**Comment by JustinJaniszewski** [comment]
I'm not sure. This could refer to a documentation file explaining how to use the code at the very least.

**Comment by yasmensarhan27** [comment]
Thank you for your response

I’ll try to find out what is it meant to be 😂

**Comment by laserlab** [comment]
Hello,

this is correct. This is meant for someone who is not involved in the homework. It should explain what to do to actually run your code.

**Comment by yasmensarhan27** [comment]
Thank You
