### ISSUE TITLE
How to undo the created branch

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G4#32]
I have created a new branch accidentally with the same documentation file. Do you know how to undo it?

**Comment by Mosaddeq107** [comment]
@poojashresthacode 
Can you please have a look into this? I hope you will get your answer with full documentation. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository

**Comment by poojashresthacode** [comment]
Thankyou @Mosaddeq107
