### ISSUE TITLE
Merge request

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework1G4#33]
I have created two branches for the multiplication unit test. If I click on the merge request, will it directly go to the main branch or to our homework group?

**Comment by yasmensarhan27** [comment]
You can choose to which one you want to merge

**Comment by tirthbha** [comment]
@yasmensarhan27 I think, it will merge to your homework branch.

**Comment by sharmistharanit** [comment]
Thank you @yasmensarhan27

**Comment by yasmensarhan27** [comment]
@sharmistharanit you have forked the project from me 
please fork it from the main homework repository
