### ISSUE TITLE
Circuit check..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G4#35]
Hi all, did you check your code for a circuit or not?
Thanks

**Comment by yasmensarhan27** [comment]
Although I’m not sure that the code itself is the one that accomplishes the classical Multiplication, Yes, it is already run on IBM QC and the results for States 0 and 1 are satisfying

**Comment by tirthbha** [comment]
@yasmensarhan27  How long it took to finish your job on the IBM QC?

**Comment by yasmensarhan27** [comment]
The code it self took 12-15 minutes and for the Unit test it took 4 hours
