### ISSUE TITLE
Fork Issue

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G4#42]
Hi, I was just checking on your group's work and noticed that @sharmistharanit has forked from @yasmensarhan27 's Homework repository Instead of the main @ubsuny repository. I believe that you need to correct this.
![image](https://github.com/ubsuny/23-Homework1G4/assets/143649458/109fe9a0-a79d-47b2-b1a9-7803cc379214)

**Comment by yasmensarhan27** [comment]
Yeah sure thank you for notifying us @sharmistharanit

**Comment by sharmistharanit** [comment]
Yaah, I copied it from Yasmin. I wanted to copy it again from the main branch. However, I was not able to copy it again. Thank you for pointing.
