### ISSUE TITLE
how to merge branch to main file

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework1G4#47]
![Screenshot (4)](https://github.com/ubsuny/23-Homework1G4/assets/143756553/1f9bf40b-66d6-4f7b-a518-d069e6493c81)
Here, it is written, push multiplication branch to poojashresthacode to create more commit. How to do that?

**Comment by pratibha77118** [comment]
I think it's up to maintainer to pull the contents of your branch to main repository.

**Comment by sharmistharanit** [comment]
@poojashresthacode You have to merge file to Yasmin's repository. She can merge to the main file as she is the maintainer of the group.
