### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework1G4#56]
I was trying to run a code in IBM QC. It was showing 245 mb has completed out of 1867 mb. However, it did not complete after 2 hrs and showed the same thing. Also, it was not showing any error. Can anyone suggest me what should I do in this case?

**Comment by yasmensarhan27** [comment]
Try on the IBM composer first to setup and run your circuit.
after it's done you can open it in IBM Quantum lab and it will be completely able to be run and return results
