### ISSUE TITLE
Can anyone suggest me a video lecture which is helpful for learning the basic of quantum computing

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework1G4#6]

**Comment by poojashresthacode** [comment]
You have one in your WhatsApp, will search for it and send it to you.

**Comment by Pranjal-Srivastava-2023** [comment]
I found these two videos helpful: 
What is quantum computing?    https://www.youtube.com/watch?v=lt4OsgmUTGI
How to program a quantum computer using Qiskit    https://www.youtube.com/watch?v=Jx7IuJMYtJM&t=3s
