### ISSUE TITLE
Commit message issue

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G4#60]
![image](https://github.com/ubsuny/23-Homework1G4/assets/143649458/539d2474-92c5-49b2-80dc-55c21e383591)
Your commit messages should not be in terms of md files.

**Comment by yasmensarhan27** [comment]
Can you clarify please

**Comment by reshnashrestha** [comment]
These are supposed to be commit messages but by default they are written in .MD ways.
