### ISSUE TITLE
Which gate are we using for multiplication in QC? Is it Hadamard gate or CNOT gate?

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework1G4#7]

**Comment by poojashresthacode** [comment]
Hadamard is appropriate in my view. But we have to combine it with XOR gate for the proper result. I have done some logical operations using it. I think would be good for multiplication.

**Comment by sharmistharanit** [comment]
![WhatsApp Image 2023-09-14 at 4 15 13 PM](https://github.com/ubsuny/23-Homework1G4/assets/143737948/9d836b83-aa57-4852-a860-2554c8e9fc97)

**Comment by yasmensarhan27** [comment]
Hi 
I think Think Classical Multiplication can't be done using Quantum Computer

**Comment by yasmensarhan27** [comment]
I'm trying to find some suitable solution for this if any

**Comment by yasmensarhan27** [comment]
Hadamard and Teffoli gates
This is explained in the Algorithm Part added in my branch
